import math
import numpy as np
import plotly.graph_objects as go
import streamlit as st
from src.ui.state import persistent_input
from src.physics.gas_dynamics import (
    normal_shock,
    nozzle,
    relief_capacity_curve,
    relief_sizing,
    RELIEF_DEMO_DEFAULTS,
)
from src.plotting import plot_relief_capacity
from src.svg_diagrams import diagram_nozzle_information, diagram_relief_valve, render_svg
from src.ui.rocket_nozzle_lab import render_rocket_nozzle_lab
from src.ui.pedagogy import (
    render_callout,
    render_derivation,
    render_plot,
    render_prose_and_latex as prose,
    render_self_check,
    render_what_to_notice,
)
from src.theme import apply_plotly_theme


def render_tab_compressible():
    st.markdown('### 12.1 Why density becomes an unknown')
    prose(r'''Compressible flow couples momentum to thermodynamics. A tire hiss, a gas jet and a process nitrogen restriction can accelerate gas until pressure, density and temperature change together. The incompressible approximation is often useful below Mach 0.3 **when heating and imposed density changes are also small**; low Mach alone does not imply constant density.

We start with steady, one-dimensional, single-phase flow of a calorically perfect ideal gas. Cross-section averages describe the stream, gravity is negligible and cp and γ are constant. All gas pressures are **absolute**, all temperatures kelvin. The gas controls below are independent of the liquid-property sidebar.
$$p=\rho RT,\quad h=c_pT,\quad c_p-c_v=R,\quad\gamma=c_p/c_v,\quad c_p=\gamma R/(\gamma-1)$$
**Sound speed.** A small, rapid disturbance is approximately isentropic. Combining the linearized mass and momentum equations gives a wave equation with a² = (∂p/∂ρ)s. Integrating ds = cv dT/T − R dρ/ρ = 0 gives p/ρ^γ constant, hence
$$a^2=\left(\frac{\partial p}{\partial\rho}\right)_s=\frac{\gamma p}{\rho}=\gamma RT,\qquad M=u/a.$$''')

    render_derivation(
        r"sound speed, from a mass and momentum balance across the wave front",
        [
            (
                "Ride the wave, so the problem becomes steady",
                r"""
                In the laboratory a sound pulse is unsteady: a front sweeps through still
                gas at speed $a$. Attach the control volume **to the front** and the picture
                stops moving. Gas now runs *into* the front at speed $a$ and leaves at
                $a-du$, while its pressure rises $p\to p+dp$ and density
                $\rho\to\rho+d\rho$. Nothing physical changed; we only removed the clock.
                This change of frame is the whole trick, and it is the same one used for
                the shock in §12.4.
                """,
            ),
            (
                "Mass balance across the front",
                r"""
                One area $A$, in and out, and no accumulation inside a front of vanishing
                thickness:
                $$\rho a A=(\rho+d\rho)(a-du)A$$
                Expand and discard $d\rho\,du$, a product of two small things:
                $$\rho a=\rho a-\rho\,du+a\,d\rho
                \quad\Longrightarrow\quad a\,d\rho=\rho\,du$$
                In words: the gas can only be compressed if the fluid behind the front is
                moving slightly slower than the fluid in front of it.
                """,
            ),
            (
                "Momentum balance on the same control volume",
                r"""
                The front is thin and the gradients are weak, so there is no wall friction
                and no body force to include. Net pressure force equals the change in
                momentum flux, $\dot m=\rho aA$:
                $$pA-(p+dp)A=\dot m\left[(a-du)-a\right]=\rho a A(-du)$$
                $$\Longrightarrow\quad dp=\rho a\,du$$
                A pressure step is exactly what is needed to decelerate the incoming stream
                by $du$.
                """,
            ),
            (
                "Eliminate the velocity change; only a thermodynamic derivative survives",
                r"""
                Two equations, one unwanted unknown. From mass $du=a\,d\rho/\rho$; put that
                into momentum:
                $$dp=\rho a\cdot\frac{a\,d\rho}{\rho}=a^{2}d\rho
                \quad\Longrightarrow\quad a^{2}=\frac{dp}{d\rho}$$
                The speed of sound is therefore not a separate physical postulate. It is
                the stiffness of the gas: how much pressure you get back for a given squeeze.
                """,
            ),
            (
                "Decide which derivative, on physical grounds",
                r"""
                $dp/d\rho$ is ambiguous until the path is named. The compression is
                **fast** — there is no time for heat to conduct out of the front, so it is
                adiabatic — and it is **weak**, so the entropy generated by the small
                gradients is second order. Adiabatic plus reversible is isentropic:
                $$a^{2}=\left(\frac{\partial p}{\partial\rho}\right)_{s}$$
                Newton famously used the *isothermal* derivative here, which drops the factor
                $\gamma$ and gives a sound speed low by $1-1/\sqrt{1.4}\approx16\%$ in air.
                The mistake was in the physics of the path, not in the algebra.
                """,
            ),
            (
                "Evaluate for a calorically perfect gas",
                r"""
                Setting $ds=c_v\,dT/T-R\,d\rho/\rho=0$ and integrating gives $p/\rho^{\gamma}$
                constant, so $\ln p=\gamma\ln\rho+\text{const}$ and
                $dp/p=\gamma\,d\rho/\rho$:
                $$a^{2}=\frac{\gamma p}{\rho}=\gamma R T$$
                Read the result: $\sqrt{RT}$ is essentially the mean thermal speed of the
                molecules. Sound is carried by molecular collisions, so a pressure signal
                simply cannot outrun the molecules that deliver it — which is why $M=u/a$,
                the ratio of bulk speed to messenger speed, decides everything that follows.
                """,
            ),
        ],
    )

    st.markdown('### 12.2 Derive the nozzle equations, one balance at a time')
    prose(r'''**1 · Mass conservation.** The same mass crosses every section. Differentiate the product and divide by ρuA.
$$\dot m=\rho uA,\qquad\frac{d\rho}{\rho}+\frac{du}{u}+\frac{dA}{A}=0$$
**2 · Momentum.** The axial pressure force accelerates the gas. For negligible wall friction and no body force, cancellation of the pressure-area terms gives
$$dp+\rho u\,du=0.$$ 
**3 · Energy.** An adiabatic nozzle has no shaft work. Static enthalpy is converted to kinetic energy, with stagnation enthalpy unchanged.
$$dh+u\,du=0,\quad c_pT+u^2/2=c_pT_0,\quad\frac{T_0}{T}=1+\frac{\gamma-1}{2}M^2$$
**4 · Entropy.** Substitute dh = −u du and dp = −ρu du into Tds = dh − dp/ρ. Then ds = 0 for this smooth, frictionless process. Integrate the ideal-gas entropy equation between the moving stream and its hypothetical isentropic rest state.
$$ds=c_p\frac{dT}{T}-R\frac{dp}{p}=0$$
$$\frac{p_0}{p}=\left(1+\frac{\gamma-1}{2}M^2\right)^{\gamma/(\gamma-1)},\quad\frac{\rho_0}{\rho}=\left(1+\frac{\gamma-1}{2}M^2\right)^{1/(\gamma-1)}$$
**5 · Area and speed.** Since dp = a²dρ along an isentrope, momentum gives dρ/ρ = −M²du/u. Substitute into continuity:
$$\boxed{\frac{dA}{A}=(M^2-1)\frac{du}{u}}$$
A converging passage accelerates subsonic flow. Supersonic flow accelerates in a diverging passage. A smooth passage through M = 1 requires a throat, but a throat alone does not guarantee sonic flow: the boundary pressures must support it.

**6 · Integrate to the area–Mach relation.** Substitute u = M√(γRT) and the stagnation ratios into mass conservation. Compare the local area with the sonic area A* at the same mass flow and stagnation state.
$$\frac{A}{A^*}=\frac{1}{M}\left[\frac{2}{\gamma+1}\left(1+\frac{\gamma-1}{2}M^2\right)\right]^{(\gamma+1)/(2(\gamma-1))}$$
For A/A* > 1 there are subsonic and supersonic mathematical branches. Boundary conditions, shocks and the nozzle geometry select the realized branch.''')

    render_derivation(
        r"the three differential balances, with the force diagram written out",
        [
            (
                "Mass: differentiate the product, do not just quote it",
                r"""
                Steady flow means the same $\dot m$ crosses every section, so
                $\rho u A$ is a constant along the duct. Take logarithms before
                differentiating — that is what turns a product into a sum:
                $$\ln\rho+\ln u+\ln A=\text{const}
                \;\Longrightarrow\;
                \frac{d\rho}{\rho}+\frac{du}{u}+\frac{dA}{A}=0$$
                Each term is now a *fractional* change, which is why they can be compared
                directly. Incompressible flow is the special case $d\rho=0$, where a
                narrowing duct must always speed the flow up.
                """,
            ),
            (
                "Momentum: the slanted wall carries a forward pressure force",
                r"""
                Take the slice between $x$ and $x+dx$, where the area goes from $A$ to
                $A+dA$. Three pressure forces act on it in the axial direction:
                $$\underbrace{pA}_{\text{inlet face}}
                \;-\;\underbrace{(p+dp)(A+dA)}_{\text{outlet face}}
                \;+\;\underbrace{p\,dA}_{\text{wall, axial component}}$$
                The third term is the one that is usually skipped. In a diverging duct the
                wall is not parallel to the axis, so the pressure acting on it has a forward
                component; its axial projection is exactly the pressure times the *projected*
                area $dA$, whatever the wall shape. Expanding the second term and dropping
                $dp\,dA$, the $p\,dA$ pieces cancel and only $-A\,dp$ survives.
                Setting that equal to the momentum flux change $\dot m\,du=\rho u A\,du$:
                $$-A\,dp=\rho u A\,du
                \;\Longrightarrow\; \boxed{dp+\rho u\,du=0}$$
                This is Euler's equation of Tab 5 written along the duct axis — no new
                physics, just a different bookkeeping of the same force balance. Friction
                and gravity were dropped, which is what makes it *ideal* nozzle flow.
                """,
            ),
            (
                "Energy: define $T_0$ rather than assume it",
                r"""
                Steady flow, no shaft work, adiabatic walls, negligible gravity. The
                first law of §1.2 then says the enthalpy plus kinetic energy per kilogram
                is the same everywhere:
                $$h+\frac{u^{2}}{2}=\text{const}
                \;\Longrightarrow\; dh+u\,du=0
                \;\Longrightarrow\; c_pT+\frac{u^{2}}{2}=c_pT_0$$
                The last step *defines* $T_0$: it is the temperature the gas would reach if
                you brought it to rest adiabatically, converting all of its ordered kinetic
                energy back into random thermal energy. Note the consistency check — combine
                $dh=c_p\,dT$ with $dh=-u\,du$ and the momentum result $dp=-\rho u\,du$ and
                you get $dh=dp/\rho$, which is $T\,ds=0$. The energy and momentum balances
                are not independent here; that is the content of Step 4 below.
                """,
            ),
            (
                r"Turn $T_0/T$ into a Mach number, using only definitions",
                r"""
                Divide the energy equation by $c_pT$:
                $$\frac{T_0}{T}=1+\frac{u^{2}}{2c_pT}$$
                Now substitute the two facts established above, $c_p=\gamma R/(\gamma-1)$ and
                $a^{2}=\gamma RT$, into the fraction:
                $$\frac{u^{2}}{2c_pT}=\frac{u^{2}(\gamma-1)}{2\gamma RT}
                =\frac{\gamma-1}{2}\frac{u^{2}}{a^{2}}=\frac{\gamma-1}{2}M^{2}$$
                $$\Longrightarrow\quad \frac{T_0}{T}=1+\frac{\gamma-1}{2}M^{2}$$
                Every stagnation ratio in this chapter is this one equation wearing a
                different exponent.
                """,
            ),
            (
                "Entropy is constant, so pressure and density follow from temperature alone",
                r"""
                Step 3 showed $ds=0$ for this smooth adiabatic acceleration. For an ideal gas
                on an isentrope, $p\propto\rho^{\gamma}$ and $p\propto\rho T$; eliminating
                $\rho$ between them gives $p\propto T^{\gamma/(\gamma-1)}$ and
                $\rho\propto T^{1/(\gamma-1)}$. Apply each to the ratio from Step 4:
                $$\frac{p_0}{p}=\left(\frac{T_0}{T}\right)^{\frac{\gamma}{\gamma-1}},
                \qquad
                \frac{\rho_0}{\rho}=\left(\frac{T_0}{T}\right)^{\frac{1}{\gamma-1}}$$
                Physically: cooling the gas as it accelerates is what pays for the kinetic
                energy, and the pressure and density fall along with the temperature because
                the gas is not being stirred or heated on the way.
                """,
            ),
            (
                r"Combine them: the area rule $dA/A=(M^{2}-1)\,du/u$",
                r"""
                Along an isentrope $dp=a^{2}d\rho$, so the momentum result becomes
                $a^{2}d\rho=-\rho u\,du$, i.e.
                $$\frac{d\rho}{\rho}=-\frac{u^{2}}{a^{2}}\frac{du}{u}=-M^{2}\frac{du}{u}$$
                Substitute that into the mass balance of Step 1:
                $$-M^{2}\frac{du}{u}+\frac{du}{u}+\frac{dA}{A}=0
                \;\Longrightarrow\;\boxed{\frac{dA}{A}=(M^{2}-1)\frac{du}{u}}$$
                Read it as a competition between two effects of speeding up: the stream needs
                *less* area because it is faster ($du/u$), and *more* area because it has
                thinned out ($-d\rho/\rho=M^{2}du/u$). Below $M=1$ the first effect wins and
                a converging duct accelerates the flow. Above $M=1$ the density loss wins and
                acceleration demands a widening duct. At $M=1$ they exactly cancel, which is
                why $dA=0$ — a throat — is the only place a smooth flow can cross the sonic
                point.
                """,
            ),
        ],
    )

    render_derivation(
        r"the area ratio $A/A^{*}$, assembled from the stagnation relations",
        [
            (
                "Choose a reference that any duct can be compared with",
                r"""
                $A^{*}$ is the area this same mass flow, with this same stagnation state,
                *would* occupy if it were exactly sonic. It is a bookkeeping device, and it
                exists whether or not the duct actually has a sonic throat.
                """,
            ),
            (
                "Write the comparison as a mass-flux ratio",
                r"""
                $\dot m=\rho uA$ is the same at both stations by definition of $A^{*}$, so
                $$\frac{A}{A^{*}}=\frac{\rho^{*}u^{*}}{\rho u}$$
                and the job reduces to expressing each factor through the stagnation state,
                which is also shared.
                """,
            ),
            (
                "Velocity ratio",
                r"""
                At the sonic reference $u^{*}=a^{*}=\sqrt{\gamma RT^{*}}$, while
                $u=M\sqrt{\gamma RT}$, so
                $$\frac{u^{*}}{u}=\frac{1}{M}\sqrt{\frac{T^{*}}{T}}
                =\frac{1}{M}\left[\frac{T^{*}}{T_0}\cdot\frac{T_0}{T}\right]^{1/2}
                =\frac{1}{M}\left[\frac{2}{\gamma+1}\left(1+\frac{\gamma-1}{2}M^{2}\right)\right]^{1/2}$$
                using $T^{*}/T_0=2/(\gamma+1)$, which is just Step 4 above evaluated at $M=1$.
                """,
            ),
            (
                "Density ratio, routed through the same stagnation state",
                r"""
                $$\frac{\rho^{*}}{\rho}=\frac{\rho^{*}}{\rho_0}\cdot\frac{\rho_0}{\rho}
                =\left[\frac{2}{\gamma+1}\left(1+\frac{\gamma-1}{2}M^{2}\right)\right]^{\frac{1}{\gamma-1}}$$
                Notice the bracket is *identical* to the one in Step 3. That is not a
                coincidence: both came from the single temperature ratio.
                """,
            ),
            (
                "Multiply, and add the exponents",
                r"""
                $$\frac{A}{A^{*}}=\frac{1}{M}\left[\frac{2}{\gamma+1}
                \left(1+\frac{\gamma-1}{2}M^{2}\right)\right]^{\frac{1}{2}+\frac{1}{\gamma-1}},
                \qquad
                \frac{1}{2}+\frac{1}{\gamma-1}=\frac{\gamma+1}{2(\gamma-1)}$$
                which is the boxed relation quoted above. The awkward exponent
                $(\gamma+1)/(2(\gamma-1))$ is nothing more than that sum of a half and a
                reciprocal.
                """,
            ),
            (
                "Why the curve has two branches",
                r"""
                $A/A^{*}\to\infty$ both as $M\to0$ (a huge, slow stream) and as
                $M\to\infty$ (a huge, rarefied stream), with a single minimum of $1$ at
                $M=1$. So every area ratio above one is met twice, once subsonic and once
                supersonic. The algebra cannot choose; only the imposed pressures and the
                presence or absence of a shock can. The second plot below is that curve.
                """,
            ),
        ],
    )
    st.markdown('### 12.3 Choking · a converging-nozzle calculator')
    render_svg(diagram_nozzle_information())
    prose(r'''A weak pressure disturbance travels at speed a relative to the gas. Its upstream-travelling branch moves at u − a in the laboratory frame: negative in subsonic flow, zero at a sonic throat. Once this ideal converging passage chokes, lowering back pressure changes the external jet rather than increasing throat mass flow. Raising back pressure enough to unchoke it restores upstream communication.''')
    prose(r'''Write mass flux using the same substitutions. At fixed reservoir p₀ and T₀, differentiating its logarithm with respect to M gives a maximum at M = 1.
$$\frac{\dot m}{A}=\frac{p_0}{\sqrt{T_0}}\sqrt{\frac{\gamma}{R}}\,M\left(1+\frac{\gamma-1}{2}M^2\right)^{-(\gamma+1)/(2(\gamma-1))}$$
$$\frac{p^*}{p_0}=\left(\frac{2}{\gamma+1}\right)^{\gamma/(\gamma-1)},\quad\frac{T^*}{T_0}=\frac{2}{\gamma+1}$$
Below the critical back-pressure ratio, a converging nozzle is sonic at its exit and further lowering the downstream pressure cannot increase its ideal mass flow. The jet adjusts outside the nozzle. The exit static pressure then differs from the imposed back pressure.
$$\dot m_* =A\frac{p_0}{\sqrt{T_0}}\sqrt{\frac{\gamma}{R}}\left(\frac{2}{\gamma+1}\right)^{(\gamma+1)/(2(\gamma-1))}$$''')

    render_derivation(
        r"why the mass-flux maximum sits exactly at $M=1$, for every gas",
        [
            (
                "Assemble the mass flux out of quantities we have already derived",
                r"""
                Mass flux is $\dot m/A=\rho u$. Write the speed as $u=Ma=M\sqrt{\gamma RT}$
                and the density from the gas law, $\rho=p/(RT)$:
                $$\frac{\dot m}{A}=\frac{p}{RT}\,M\sqrt{\gamma RT}=p\,M\sqrt{\frac{\gamma}{RT}}$$
                Nothing has been assumed yet — this is an identity for any ideal-gas stream.
                """,
            ),
            (
                "Refer everything to the reservoir, which is what the operator actually sets",
                r"""
                A valve at the back does not change $p_0$ or $T_0$; it changes $M$. So
                substitute $p=p_0\left(1+\frac{\gamma-1}{2}M^{2}\right)^{-\gamma/(\gamma-1)}$
                and $T=T_0\left(1+\frac{\gamma-1}{2}M^{2}\right)^{-1}$. The temperature enters
                as $T^{-1/2}$, so the two exponents add:
                $$-\frac{\gamma}{\gamma-1}+\frac{1}{2}
                =\frac{-2\gamma+\gamma-1}{2(\gamma-1)}=-\frac{\gamma+1}{2(\gamma-1)}$$
                $$\frac{\dot m}{A}=\frac{p_0}{\sqrt{T_0}}\sqrt{\frac{\gamma}{R}}\;
                M\left(1+\frac{\gamma-1}{2}M^{2}\right)^{-\frac{\gamma+1}{2(\gamma-1)}}$$
                The whole $M$-dependence is now one factor rising linearly and one falling
                like a power — a product that must have an interior maximum.
                """,
            ),
            (
                "Maximise by differentiating the logarithm",
                r"""
                A positive function and its logarithm peak at the same place, and the log
                turns the product into a sum that differentiates in one line. With everything
                in front of $M$ held fixed:
                $$\frac{d}{dM}\ln\frac{\dot m}{A}
                =\frac{1}{M}-\frac{\gamma+1}{2(\gamma-1)}\cdot
                \frac{(\gamma-1)M}{1+\frac{\gamma-1}{2}M^{2}}
                =\frac{1}{M}-\frac{(\gamma+1)M}{2+(\gamma-1)M^{2}}$$
                """,
            ),
            (
                r"Set it to zero and watch $\gamma$ cancel",
                r"""
                $$2+(\gamma-1)M^{2}=(\gamma+1)M^{2}
                \;\Longrightarrow\; 2=2M^{2}
                \;\Longrightarrow\; M=1$$
                Every trace of the gas has vanished. Air, helium, steam or refrigerant: the
                throat of a converging passage delivers its greatest possible mass flux at
                exactly sonic conditions. This is the same cancellation as the area rule —
                the gain in speed and the loss in density change at equal rates at $M=1$.
                """,
            ),
            (
                "Evaluate the sonic state and the choked flux",
                r"""
                Put $M=1$ into the stagnation ratios; the bracket becomes $(\gamma+1)/2$:
                $$\frac{T^{*}}{T_0}=\frac{2}{\gamma+1},\qquad
                \frac{p^{*}}{p_0}=\left(\frac{2}{\gamma+1}\right)^{\frac{\gamma}{\gamma-1}}$$
                and into the flux formula of Step 2:
                $$\frac{\dot m_{*}}{A}=\frac{p_0}{\sqrt{T_0}}\sqrt{\frac{\gamma}{R}}
                \left(\frac{2}{\gamma+1}\right)^{\frac{\gamma+1}{2(\gamma-1)}}$$
                For air ($\gamma=1.4$) the pressure ratio is $0.528$: the back pressure must
                fall below about half the reservoir pressure before the nozzle chokes.
                """,
            ),
            (
                "The physical reason the answer stops changing",
                r"""
                A pressure disturbance travels at $a$ relative to the gas, so in the
                laboratory its upstream-running branch moves at $u-a$. That is negative in
                subsonic flow — news gets upstream — and **zero** at a sonic throat. Once the
                throat reaches $M=1$, a further drop in back pressure literally cannot send
                the message upstream, so the reservoir never learns to push harder. The
                mathematics above says the maximum is at $M=1$; this says why the flow cannot
                be pushed past it.
                """,
            ),
        ],
    )
    a,b,c=st.columns(3)
    p0=persistent_input(a.number_input, 'Reservoir stagnation pressure [kPa absolute]',min_value=.001,value=500., key="tab_compressible_reservoir_stagnation_pressure_kpa_absolute")*1000
    t0=persistent_input(a.number_input, 'Reservoir stagnation temperature [K]',min_value=1.,value=300., key="tab_compressible_reservoir_stagnation_temperature_k")
    pb=persistent_input(b.number_input, 'Back pressure [kPa absolute]',min_value=.001,value=100., key="tab_compressible_back_pressure_kpa_absolute")*1000
    d=persistent_input(b.number_input, 'Converging-nozzle exit diameter [mm]',min_value=.01,value=5., key="tab_compressible_converging_nozzle_exit_diameter_mm")/1000
    gamma=persistent_input(c.number_input, 'Nozzle γ',min_value=1.01,max_value=1.67,value=1.4, key="tab_compressible_nozzle")
    gasr=persistent_input(c.number_input, 'Nozzle gas constant [J/(kg·K)]',min_value=1.,value=287.05, key="tab_compressible_nozzle_gas_constant_j_kg_k")
    area=math.pi*d*d/4; result=nozzle(p0,t0,pb,area,gamma,gasr)
    a,b,c,e=st.columns(4)
    a.metric('Mass flow',f'{result["mass_flow"]:.5f} kg/s'); b.metric('Exit Mach',f'{result["mach"]:.3f}'); c.metric('Exit static T',f'{result["temperature"]:.2f} K'); e.metric('Exit static pressure',f'{result["pressure"]/1000:.2f} kPa abs')
    if pb>=p0:
        st.info('No forward flow: back pressure is at or above reservoir pressure. This calculator does not model reverse flow.')
    else:
        st.info(f'{"Choked" if result["choked"] else "Unchoked"} · critical back-pressure ratio = {result["critical_ratio"]:.4f}. Ideal smooth nozzle, discharge coefficient = 1.')
    ratios=np.linspace(.02,1,160)
    fig=go.Figure(go.Scatter(x=ratios,y=[nozzle(p0,t0,p0*r,area,gamma,gasr)['mass_flow'] for r in ratios],name='Ideal mass flow'))
    fig.add_vline(x=result['critical_ratio'],line_dash='dash',annotation_text='Sonic threshold',annotation_position='top left')
    fig.add_trace(go.Scatter(x=[min(pb/p0,1)],y=[result['mass_flow']],mode='markers',marker=dict(size=12),name='Your input (capped at ratio 1)'))
    fig.update_layout(title='Lowering back pressure eventually stops increasing flow',xaxis_title='Back pressure / reservoir stagnation pressure',yaxis_title='Mass flow [kg/s]',height=400)
    apply_plotly_theme(fig); render_plot(fig,'nozzle-choking')
    machs=np.concatenate([np.linspace(.12,1,80),np.linspace(1.01,3,80)])
    ar=1/machs*(2/(gamma+1)*(1+(gamma-1)*machs*machs/2))**((gamma+1)/(2*(gamma-1)))
    fig=go.Figure(go.Scatter(x=machs,y=ar,name='Area–Mach relation'))
    fig.update_layout(title='One area ratio, two possible Mach numbers',xaxis_title='Mach number',yaxis_title='A / A*',height=360)
    apply_plotly_theme(fig); render_plot(fig,'area-mach')
    st.caption('[NASA: isentropic flow relations](https://www.grc.nasa.gov/www/k-12/airplane/isentrop.html). Real orifices, valves and relief devices need geometry-dependent discharge coefficients and appropriate property models; this calculator represents an ideal converging nozzle.')
    st.markdown('### 12.4 A shock breaks the isentropic assumption')
    prose(r'''A normal shock is a very thin irreversible compression in supersonic flow. Integrate conservation across it instead of applying a smooth isentropic relation through it. Let 1 be upstream and 2 downstream, with equal cross-sectional areas.
$$\rho_1u_1=\rho_2u_2,\quad p_1+\rho_1u_1^2=p_2+\rho_2u_2^2,\quad c_pT_1+u_1^2/2=c_pT_2+u_2^2/2$$
**Eliminate velocity.** Set r = ρ₂/ρ₁ so u₂ = u₁/r. Momentum gives p₂/p₁ = 1 + γM₁²(1 − 1/r). The ideal-gas law gives T₂/T₁ = (p₂/p₁)/r. Substitute these into energy and solve the resulting quadratic; discard the unchanged-flow root r = 1 for M₁ > 1.
$$\frac{\rho_2}{\rho_1}=\frac{(\gamma+1)M_1^2}{2+(\gamma-1)M_1^2},\qquad\frac{p_2}{p_1}=1+\frac{2\gamma}{\gamma+1}(M_1^2-1)$$
$$M_2^2=\frac{1+(\gamma-1)M_1^2/2}{\gamma M_1^2-(\gamma-1)/2},\quad\frac{T_2}{T_1}=\frac{p_2/p_1}{\rho_2/\rho_1}$$
Static pressure and temperature rise; Mach number drops below one. Stagnation temperature stays constant because there is no heat or work. Entropy rises and stagnation pressure falls. Compute each side's stagnation pressure separately:
$$\frac{p_{02}}{p_{01}}=\frac{p_2}{p_1}\left[\frac{1+(\gamma-1)M_2^2/2}{1+(\gamma-1)M_1^2/2}\right]^{\gamma/(\gamma-1)}<1$$''')

    render_derivation(
        r"the shock relations, including the quadratic and the root that is thrown away",
        [
            (
                "Why conservation still works when nothing else does",
                r"""
                A shock is a few mean free paths thick, and inside it the gradients are so
                violent that viscous dissipation and heat conduction are *first-order* terms,
                not corrections. Every smooth-flow relation of §12.2 fails there. But the
                three conservation laws are integral statements: they relate the state on one
                side to the state on the other and never ask what happened in between. So we
                deliberately stop describing the interior and box it up.
                """,
            ),
            (
                "The three balances across a constant-area box",
                r"""
                Areas are equal, the box is thin (no wall friction area, no volume for heat
                storage), and there is no shaft work:
                $$\rho_1u_1=\rho_2u_2,\qquad
                p_1+\rho_1u_1^{2}=p_2+\rho_2u_2^{2},\qquad
                c_pT_1+\tfrac{1}{2}u_1^{2}=c_pT_2+\tfrac{1}{2}u_2^{2}$$
                Three equations for the three unknowns $p_2,\rho_2,u_2$ — the problem is
                closed without any model of the shock structure.
                """,
            ),
            (
                "Carry one unknown, the compression ratio",
                r"""
                Let $r=\rho_2/\rho_1$. Continuity immediately gives $u_2=u_1/r$: this is the
                single variable everything else will be written in terms of. Momentum then
                becomes
                $$p_2-p_1=\rho_1u_1^{2}-\rho_2u_2^{2}=\rho_1u_1^{2}\left(1-\frac{1}{r}\right)$$
                and the useful identity
                $\rho u^{2}=\rho M^{2}a^{2}=\rho M^{2}\gamma RT=\gamma pM^{2}$ converts the
                prefactor into a Mach number:
                $$\frac{p_2}{p_1}=1+\gamma M_1^{2}\left(1-\frac{1}{r}\right)$$
                """,
            ),
            (
                "Put energy in the same variables and clear the fractions",
                r"""
                Write $c_pT=\dfrac{\gamma}{\gamma-1}\dfrac{p}{\rho}$ and use
                $p_1/\rho_1=u_1^{2}/(\gamma M_1^{2})$. Dividing the energy equation by
                $u_1^{2}$ and multiplying by $2(\gamma-1)M_1^{2}$ leaves
                $$2+(\gamma-1)M_1^{2}
                =\frac{2P}{r}+\frac{(\gamma-1)M_1^{2}}{r^{2}},
                \qquad P\equiv\frac{p_2}{p_1}$$
                Substituting $P$ from Step 3 and multiplying through by $r^{2}$ gives a plain
                quadratic in $r$:
                $$\left[2+(\gamma-1)M_1^{2}\right]r^{2}
                -\left[2+2\gamma M_1^{2}\right]r
                +(\gamma+1)M_1^{2}=0$$
                """,
            ),
            (
                r"Both roots are real, and one of them is $r=1$",
                r"""
                Add the coefficients: $\left[2+(\gamma-1)M_1^{2}\right]-\left[2+2\gamma
                M_1^{2}\right]+(\gamma+1)M_1^{2}=0$, so $r=1$ solves it identically. That is
                not an artefact — "nothing happens" always satisfies conservation across an
                imaginary surface in a uniform stream. Divide it out:
                $$(r-1)\left\{\left[2+(\gamma-1)M_1^{2}\right]r-(\gamma+1)M_1^{2}\right\}=0
                \;\Longrightarrow\;
                \boxed{\frac{\rho_2}{\rho_1}=\frac{(\gamma+1)M_1^{2}}{2+(\gamma-1)M_1^{2}}}$$
                """,
            ),
            (
                "Back-substitute for pressure, temperature and downstream Mach",
                r"""
                With $1-1/r=2(M_1^{2}-1)/\left[(\gamma+1)M_1^{2}\right]$, Step 3 collapses to
                $$\frac{p_2}{p_1}=1+\frac{2\gamma}{\gamma+1}(M_1^{2}-1)$$
                The gas law gives $T_2/T_1=(p_2/p_1)/r$, and since
                $M_2^{2}=M_1^{2}/(rP)$ (from $u_2=u_1/r$ and $a^{2}\propto T$),
                $$M_2^{2}=\frac{1+\frac{\gamma-1}{2}M_1^{2}}{\gamma M_1^{2}-\frac{\gamma-1}{2}}$$
                Every quoted shock formula has now been produced from the three balances alone.
                """,
            ),
            (
                "The second law throws away half of the solutions",
                r"""
                The algebra is perfectly happy with $M_1<1$: it returns $r<1$, an expansion
                jump. Compute the entropy change and it comes out **negative**, which no
                adiabatic process may do. So a normal shock exists only for $M_1>1$, and it
                always compresses. This is the one place in the chapter where a conservation
                law is not enough and the second law does the selecting.
                """,
            ),
            (
                "Stagnation temperature survives; stagnation pressure does not",
                r"""
                No heat and no work means $h_0$ is conserved, so $T_{02}=T_{01}$ exactly —
                the gas ends up just as hot when brought to rest, having converted ordered
                kinetic energy into thermal energy. But the entropy rise inside the shock is
                real, and for an ideal gas at fixed $T_0$,
                $$\frac{p_{02}}{p_{01}}=\exp\!\left(-\frac{\Delta s}{R}\right)<1$$
                which is the loss of *usable* pressure. That is the practical cost of a shock:
                nothing is lost from the energy books, but capacity to do work is.
                """,
            ),
        ],
    )
    m1=persistent_input(st.slider, 'Upstream normal-shock Mach number',1.,5.,2.,step=.05, key="tab_compressible_upstream_normal_shock_mach_number")
    shock=normal_shock(m1,gamma)
    a,b,c,e=st.columns(4)
    a.metric('Downstream Mach',f'{shock["mach2"]:.3f}'); b.metric('Static p₂ / p₁',f'{shock["pressure_ratio"]:.3f}'); c.metric('Static T₂ / T₁',f'{shock["temperature_ratio"]:.3f}'); e.metric('Stagnation p₀₂ / p₀₁',f'{shock["stagnation_pressure_ratio"]:.4f}')
    st.caption('[NASA: normal-shock conservation relations](https://www.grc.nasa.gov/WWW/k-12/airplane/normal.html).')
    render_rocket_nozzle_lab()
    st.markdown('### 12.6 Long ducts: friction and heating can also choke flow')
    prose(r'''**Fanno flow: constant area, adiabatic, friction present.** Continuity gives dρ/ρ = −du/u. Energy keeps T₀ constant. The wall force on a length dx of circular pipe is τwπDdx, so dividing by area gives 4τw dx/D. With the Fanning factor fF = 2τw/(ρu²) used throughout this course, momentum becomes
$$dp+\rho u\,du+\frac{4f_F}{D}\frac{\rho u^2}{2}dx=0,\quad c_p dT=-u\,du$$
Use the gas law, dp/p = dρ/ρ + dT/T. After substitution, the two velocity terms combine into (M²−1)du/u:
$$\frac{du}{u}=\frac{\gamma M^2}{2(1-M^2)}\frac{4f_F\,dx}{D}$$
Friction accelerates a subsonic gas and decelerates a supersonic gas toward M = 1. Pressure energy, density and speed adjust together; the incompressible intuition “friction always slows flow downstream” is inadequate. The remaining nondimensional length to choking is
$$\int_x^{x^*}\frac{4f_F}{D}dx=\frac{1-M^2}{\gamma M^2}+\frac{\gamma+1}{2\gamma}\ln\left[\frac{(\gamma+1)M^2}{2+(\gamma-1)M^2}\right].$$
For constant fF and D the left side is 4fF L*/D. Aerospace tables print the same group as fD L*/D with the Darcy factor, fD = 4fF — identical numbers, so do not apply the factor of four twice. A specified inlet state cannot support an arbitrarily long duct at the same mass flow; the global boundary-value solution must adjust.

**Rayleigh flow: constant area, heat transfer, negligible friction.** Mass flux G = ρu is constant; momentum gives p + ρu² constant. Divide momentum by p and compare with the sonic reference on the same Rayleigh line:
$$\frac{p}{p^*}=\frac{\gamma+1}{1+\gamma M^2},\quad\frac{T}{T^*}=M^2\left(\frac{\gamma+1}{1+\gamma M^2}\right)^2$$
Energy now gives dq = dh₀ = cp dT₀. Multiplying the static-temperature ratio by the ratio of stagnation corrections yields
$$\frac{T_0}{T_0^*}=\frac{2(\gamma+1)M^2[1+(\gamma-1)M^2/2]}{(1+\gamma M^2)^2}.$$
Adding heat drives either branch toward sonic conditions, where T₀ is maximal along the line. Removing heat drives it away. Static temperature is not monotonic over the entire subsonic branch: it reaches a maximum at M = 1/√γ. Real heated rough pipes combine both effects; separate Fanno and Rayleigh formulas cannot simply be added.''')

    render_derivation(
        r"Fanno flow: from a wall-shear force to $du/u=\frac{\gamma M^{2}}{2(1-M^{2})}\frac{4f_F\,dx}{D}$",
        [
            (
                "Turn the wall shear into a term the momentum balance can use",
                r"""
                Friction acts on the **wetted perimeter**, not on the cross-section. Over a
                length $dx$ of round pipe the retarding force is $\tau_w(\pi D\,dx)$. The
                momentum balance is written per unit flow area $\pi D^{2}/4$, so divide:
                $$\frac{\tau_w\pi D\,dx}{\pi D^{2}/4}=\frac{4\tau_w}{D}dx$$
                The factor $4/D$ is the surface-to-volume ratio of a cylinder — pure geometry,
                and the reason small pipes are so much more frictional. Now insert the Fanning
                definition $\tau_w=f_F\rho u^{2}/2$ (Tab 2):
                $$\frac{4}{D}\cdot\frac{f_F\rho u^{2}}{2}dx=\frac{4f_F}{D}\frac{\rho u^{2}}{2}dx$$
                """,
            ),
            (
                "Collect the four statements that describe the duct",
                r"""
                Constant area, adiabatic, with friction:
                $$\text{momentum: } dp+\rho u\,du+\frac{4f_F}{D}\frac{\rho u^{2}}{2}dx=0$$
                $$\text{mass: } \frac{d\rho}{\rho}+\frac{du}{u}=0 \quad(dA=0)$$
                $$\text{energy: } c_p\,dT+u\,du=0 \quad(\text{no heat, no work}\Rightarrow T_0\text{ fixed})$$
                $$\text{state: } \frac{dp}{p}=\frac{d\rho}{\rho}+\frac{dT}{T}$$
                Friction appears **only** in the momentum equation. It does not remove energy
                from the gas — it converts ordered kinetic energy into internal energy, which
                is why $T_0$ is still constant.
                """,
            ),
            (
                "Express temperature and pressure changes through the velocity change",
                r"""
                From the energy equation, dividing by $c_pT$ and using
                $u^{2}/(c_pT)=(\gamma-1)M^{2}$ exactly as in §12.2:
                $$\frac{dT}{T}=-(\gamma-1)M^{2}\frac{du}{u}$$
                and then from mass plus state:
                $$\frac{dp}{p}=-\frac{du}{u}-(\gamma-1)M^{2}\frac{du}{u}
                =-\left[1+(\gamma-1)M^{2}\right]\frac{du}{u}$$
                """,
            ),
            (
                r"Divide the momentum equation by $p$ and let the terms combine",
                r"""
                Using $\rho u^{2}/p=\gamma M^{2}$ again:
                $$-\left[1+(\gamma-1)M^{2}\right]\frac{du}{u}
                +\gamma M^{2}\frac{du}{u}
                +\frac{\gamma M^{2}}{2}\frac{4f_F\,dx}{D}=0$$
                The two velocity coefficients collapse:
                $\gamma M^{2}-1-(\gamma-1)M^{2}=M^{2}-1$, so
                $$(M^{2}-1)\frac{du}{u}=-\frac{\gamma M^{2}}{2}\frac{4f_F\,dx}{D}
                \;\Longrightarrow\;
                \boxed{\frac{du}{u}=\frac{\gamma M^{2}}{2(1-M^{2})}\frac{4f_F\,dx}{D}}$$
                """,
            ),
            (
                "Read the sign, and abandon the incompressible intuition",
                r"""
                $4f_F\,dx/D$ is positive. So for $M<1$ the bracket is positive and friction
                **accelerates** the gas; for $M>1$ it is negative and friction **decelerates**
                it. Both move the flow toward $M=1$. This is not paradoxical: friction drops
                the pressure, the gas expands, and in a constant-area duct a less dense gas
                must move faster to carry the same $\dot m$. That expansion outweighs the
                direct drag as long as the flow is subsonic.
                """,
            ),
            (
                "Integrate to the choking length",
                r"""
                Convert to Mach number. From $u=M\sqrt{\gamma RT}$ and
                $T=T_0\left(1+\frac{\gamma-1}{2}M^{2}\right)^{-1}$,
                $$\frac{du}{u}=\frac{dM}{M}\cdot\frac{1}{1+\frac{\gamma-1}{2}M^{2}}
                \;\Longrightarrow\;
                \frac{4f_F}{D}dx=\frac{4(1-M^{2})}{\gamma M^{3}\left[2+(\gamma-1)M^{2}\right]}dM$$
                The integrand is a rational function of $M$; partial fractions in $M^{2}$
                give the closed form quoted above, whose value is $0$ at $M=1$ — the duct
                length at which the flow chokes. A duct longer than $L^{*}$ cannot pass the
                assumed mass flow at the assumed inlet state; the whole solution readjusts.
                """,
            ),
            (
                "One factor-of-four trap",
                r"""
                Everything here is **Fanning** $f_F$, as everywhere else in this course, so
                the choking group reads $4f_FL^{*}/D$. Most gas-dynamics tables and charts
                print the same quantity as $f_DL^{*}/D$ with the Darcy factor $f_D=4f_F$ —
                identical numbers, different label. Mixing the two conventions moves a
                predicted choking length by a factor of four.
                """,
            ),
        ],
    )

    render_derivation(
        r"Rayleigh flow: heat addition with no friction, and why heating drives flow to $M=1$",
        [
            (
                "Momentum with no friction term is an algebraic constraint",
                r"""
                Constant area, negligible wall shear, so the only axial forces are the two
                end pressures:
                $$p+\rho u^{2}=\text{const}$$
                Using $\rho u^{2}=\gamma pM^{2}$, this is $p(1+\gamma M^{2})=\text{const}$.
                Comparing any state with the sonic state on the same line ($M=1$):
                $$\frac{p}{p^{*}}=\frac{\gamma+1}{1+\gamma M^{2}}$$
                Heat does not appear. That is the point: heating changes the state *along*
                this fixed line, it does not move the line.
                """,
            ),
            (
                "Mass conservation supplies the second constraint",
                r"""
                $G=\rho u$ is constant, so $\rho\propto1/u$. With $T=p/(\rho R)$ we get
                $T\propto p\,u\propto pM\sqrt{T}$, hence $\sqrt{T}\propto pM$ and
                $$\frac{T}{T^{*}}=M^{2}\left(\frac{p}{p^{*}}\right)^{2}
                =M^{2}\left(\frac{\gamma+1}{1+\gamma M^{2}}\right)^{2}$$
                Two conservation laws have fixed the entire locus of possible states without
                any reference to how much heat was supplied.
                """,
            ),
            (
                "Energy is what heat actually controls",
                r"""
                With no work and no friction, the first law per kilogram reads
                $$\delta q=dh_0=c_p\,dT_0$$
                so the heat added is measured by the rise in **stagnation** temperature, not
                static. Multiplying the static ratio of Step 2 by the stagnation correction
                $\left(1+\frac{\gamma-1}{2}M^{2}\right)$, normalised at $M=1$:
                $$\frac{T_0}{T_0^{*}}
                =\frac{2(\gamma+1)M^{2}\left[1+\frac{\gamma-1}{2}M^{2}\right]}{(1+\gamma M^{2})^{2}}$$
                """,
            ),
            (
                r"This ratio has its maximum at $M=1$, which is the whole story",
                r"""
                $T_0/T_0^{*}\le1$ with equality only at $M=1$ — differentiating the
                expression above and setting it to zero returns $M=1$ for every $\gamma$,
                just as the mass-flux maximum did. Since adding heat can only raise $T_0$,
                heating **must** push the state toward $M=1$ from either branch, and once
                there, no further heat can be added at that mass flow: **thermal choking**.
                Removing heat drives the state away from sonic. A combustor can be shut down
                by its own heat release.
                """,
            ),
            (
                r"The counter-intuitive maximum of static $T$",
                r"""
                Differentiate $T/T^{*}=M^{2}(\gamma+1)^{2}/(1+\gamma M^{2})^{2}$:
                the numerator of $d/dM$ vanishes when
                $(1+\gamma M^{2})-2\gamma M^{2}=0$, i.e. at
                $$M=1/\sqrt{\gamma}\approx0.845\ \text{for air}$$
                So between $M=1/\sqrt{\gamma}$ and $M=1$ you can **add** heat and watch the
                static temperature **fall**: the acceleration the heat causes converts thermal
                energy into kinetic energy faster than the heat supplies it. $T_0$ still rises
                throughout, which is why the energy books balance.
                """,
            ),
            (
                "Why the two models cannot be added",
                r"""
                Fanno assumed no heat; Rayleigh assumed no friction. Each derivation dropped
                a term the other kept, and both effects enter the *same* momentum and energy
                equations non-linearly through $M$. A real hot rough duct needs the coupled
                system integrated together; superposing the two closed forms has no
                justification, even though both push toward $M=1$.
                """,
            ),
        ],
    )
    st.caption('[NPTEL: Fanno flow](https://archive.nptel.ac.in/content/storage2/courses/112103021/module2/lec15/1.html) · [Rayleigh flow](https://archive.nptel.ac.in/content/storage2/courses/112103021/module2/lec14/1.html).')
    st.markdown('### 12.7 Use the model in everyday and process problems')
    st.dataframe([
        {'Situation':'Air escaping a tire','First model':'Reservoir + restriction; test choking','What changes':'Reservoir pressure and temperature fall with time; steady nozzle relation is an instantaneous approximation.'},
        {'Situation':'Blowing through a narrow nozzle','First model':'Mass + momentum + energy','What changes':'The accelerating gas cools statically even though its stagnation temperature stays nearly constant.'},
        {'Situation':'Nitrogen supply to a reactor','First model':'Absolute-pressure boundaries, valve/nozzle and gas-line losses','What changes':'Check mass flow rather than assuming equal inlet/outlet volumetric flow; use compressible pipe modeling for large density changes.'},
        {'Situation':'Compressor with intercooler','First model':'Shaft work followed by heat rejection','What changes':'Stage discharge warms; cooling reduces the next stage’s specific volume and work.'},
        {'Situation':'Hot process gas in a duct','First model':'Coupled friction and heat transfer','What changes':'Mass, momentum, energy and properties must be solved together; choking limits admissible flow.'},
        {'Situation':'Aerosol can, steam or relief discharge','First model':'Check phase and real-gas properties first','What changes':'Flashing, condensation and two-phase choking can invalidate the perfect-gas model.'},
    ],hide_index=True,width='stretch')
    st.markdown('**Before CFD.** The next chapter solves incompressible Navier–Stokes. Its pressure correction enforces approximately zero velocity divergence; it does not solve the gas energy equation, shock waves or sonic choking. Compressible CFD instead couples density, momentum and total energy with an equation of state and requires suitable wave-resolving numerical fluxes.')

    st.markdown('### 12.8 Why choking is the foundation of pressure relief design')
    st.markdown(
        'The mass-flow plateau gives a useful first model for gas relief capacity. '
        'This section sizes an idealized fixed-area restriction for a specified mass rate, '
        'then separates that flow model from the behavior of a real valve and its piping.'
    )
    render_svg(diagram_relief_valve())

    st.markdown('#### 12.8.1 The design fact')
    prose(r'''Start with a defined gas-release scenario, such as a blocked outlet. The required release rate W comes from that scenario's mass and energy balances. The flow model then estimates the area needed to pass W at a specified upstream state.

For an incompressible or unchoked gas flow, capacity depends on pressures on **both** sides. In a shared discharge header the downstream pressure is itself part of a network calculation.

For an ideal fixed-area gas passage, choking removes back pressure from the mass-flux equation **while p_b/p_0 remains at or below the critical ratio**. A small downstream disturbance cannot propagate upstream through the sonic throat, and
$$G=\frac{\dot m}{A}=p_0\sqrt{\frac{\gamma}{RT_0}}\left(\frac{2}{\gamma+1}\right)^{\frac{\gamma+1}{2(\gamma-1)}}$$
contains no back pressure at all. The required area follows immediately:
$$A=\frac{W}{K_d\,G}$$
with $W$ the required relief rate and $K_d$ the discharge coefficient. **This independence holds at fixed upstream state, gas properties, area and coefficient.** Real valve lift, inlet losses and discharge-system effects are outside this ideal flow model.''')
    render_derivation(
        r"the sizing equation $A=W/(K_d G)$, and what each symbol is carrying",
        [
            (
                "G is not a new result; it is §12.3 evaluated at the throat",
                r"""
                The mass flux above is the choked flux derived in §12.3 by maximising
                $\rho u$ over $M$ and finding the maximum at $M=1$:
                $$G=\frac{\dot m_{*}}{A}=p_0\sqrt{\frac{\gamma}{RT_0}}
                \left(\frac{2}{\gamma+1}\right)^{\frac{\gamma+1}{2(\gamma-1)}}$$
                Nothing about relief hardware entered that derivation — it is a property of
                the *gas and its upstream state*, with units of kg per second per square
                metre. Note that $p_0$ enters linearly and $T_0$ as $T_0^{-1/2}$; those two
                exponents are the whole of §12.8.2.
                """,
            ),
            (
                "Mass rate is flux times area — the only step that involves the device",
                r"""
                An ideal passage of throat area $A$ would pass $\dot m=GA$. A real device
                passes less, because the stream contracts (a vena contracta) and because the
                passage is not a smooth nozzle. Both are lumped into one measured number:
                $$W=K_d\,G\,A$$
                $K_d$ is therefore not physics; it is a certified, measured correction that
                belongs to a specific device, and it is the reason this calculation cannot
                by itself select a valve.
                """,
            ),
            (
                "Rearrange for the unknown, then take the square root for a bore",
                r"""
                $$A=\frac{W}{K_d\,G},\qquad d=\sqrt{\frac{4A}{\pi}}$$
                The second step is where the fourth-root behaviour of §12.8.2 comes from:
                because $A\propto\sqrt{T_0}$ and $d\propto\sqrt{A}$, the required *bore*
                grows only as $T_0^{1/4}$. Quadrupling the absolute relieving temperature
                doubles the area but increases the diameter by only $41\%$.
                """,
            ),
            (
                "Check the assumption before using any of it",
                r"""
                $G$ is the *choked* flux, so the equation is only valid while
                $p_b/p_0\le\left(2/(\gamma+1)\right)^{\gamma/(\gamma-1)}$. Above that ratio the
                throat is subsonic, back pressure re-enters the mass-flux expression, and the
                required area is larger than this formula returns. The calculator below tests
                that ratio first, and says so.
                """,
            ),
        ],
    )
    render_callout(
        """
        **For air-like gases the threshold is approximately $p_0/p_b = 1.9$.** The critical ratio is
        $(2/(\\gamma+1))^{\\gamma/(\\gamma-1)} = 0.528$ for $\\gamma = 1.4$, so anything
        an ideal passage with sufficient upstream-to-downstream absolute pressure ratio
        chokes. Always calculate the ratio for the stated gas and back pressure;
        a high upstream pressure alone is not enough.
        """,
        title="Check the pressure ratio first",
    )

    st.markdown('#### 12.8.2 What the formula tells a designer')
    prose(r'''Three consequences fall straight out of $G \propto p_0/\sqrt{T_0}$, and each one is a mistake someone has made.

**1 · Lower back pressure does not increase ideal choked mass flux.** With upstream state, gas and coefficient fixed, lowering back pressure further adds no capacity. In this model a larger required rate needs more area. A real undersized system requires reassessing the release scenario, device and piping; changing a set pressure is not a general remedy.

**2 · Higher temperature needs more area at the same required mass rate.** $G$ falls as $1/\sqrt{T_0}$. Therefore $A\propto\sqrt{T_0}$, but the equivalent diameter scales only as $d\propto T_0^{1/4}$. A different release scenario may also change W and the gas state; temperature alone does not define a fire case.

**3 · Back pressure matters through two distinct mechanisms.** Once p_b/p_0 exceeds the critical ratio, flow unchokes and mass flux falls. Separately, back pressure can affect a real valve's opening and lift even while its flow is choked. Those effects depend on device design and service conditions; this fixed-area model cannot predict them.''')

    st.markdown('#### 12.8.3 Sizing calculator')
    defaults = RELIEF_DEMO_DEFAULTS
    rl1, rl2, rl3 = st.columns(3)
    w_req = persistent_input(rl1.number_input, 'Required relief rate W [kg/s]', min_value=.001, max_value=500.,
                             value=defaults['required_flow'], step=.5, key='relief_w')
    p_set = persistent_input(rl1.number_input, 'Relieving pressure p₀ [bar a]', min_value=1.05, max_value=400.,
                             value=defaults['p0'] / 1e5, step=.5, key='relief_p0')
    t_rel = persistent_input(rl2.number_input, 'Relieving temperature T₀ [K]', min_value=100., max_value=1500.,
                             value=defaults['t0'], step=5., key='relief_t0')
    p_back = persistent_input(rl2.number_input, 'Total back pressure [bar a]', min_value=.05, max_value=390.,
                              value=defaults['back_pressure'] / 1e5, step=.1, key='relief_pb')
    kd = persistent_input(rl3.number_input, 'Discharge coefficient K_d', min_value=.1, max_value=1.,
                          value=defaults['discharge_coefficient'], step=.005, key='relief_kd')
    gamma_r = persistent_input(rl3.number_input, 'γ', min_value=1.01, max_value=1.7, value=defaults['gamma'], step=.01,
                               key='relief_gamma')
    r_gas = persistent_input(rl3.number_input, 'Gas constant R [J/(kg·K)]', min_value=20., max_value=4200.,
                             value=defaults['gas_constant'], step=1., key='relief_r')

    if p_back >= p_set:
        st.error('Back pressure must be below the relieving pressure, or nothing flows out.')
    else:
        sizing = relief_sizing(w_req, p_set * 1e5, t_rel, p_back * 1e5,
                               gamma_r, r_gas, kd)
        s1, s2, s3, s4 = st.columns(4)
        s1.metric('Required throat area', f"{sizing['area'] * 1e6:.0f} mm²")
        s2.metric('Equivalent bore', f"{sizing['diameter'] * 1000:.1f} mm")
        s3.metric('Mass flux G', f"{sizing['mass_flux']:.0f} kg/(s·m²)")
        s4.metric('p_b / p₀', f"{sizing['back_pressure_ratio']:.3f}",
                  'choked' if sizing['choked'] else 'NOT choked')

        if sizing['choked']:
            st.success(
                f"Choked: {sizing['back_pressure_ratio']:.3f} is below the critical ratio "
                f"{sizing['critical_ratio']:.3f}. At fixed upstream state, gas, area and coefficient, "
                "lowering back pressure further does not increase this model's capacity."
            )
        else:
            st.warning(
                f"**Not choked.** {sizing['back_pressure_ratio']:.3f} exceeds the critical "
                f"ratio {sizing['critical_ratio']:.3f}, so the throat now feels the "
                f"downstream pressure and capacity has fallen "
                f"{100 * sizing['capacity_loss_vs_choked']:.1f}% below the choked value. "
                "The area above already accounts for the flow effect. It does not account "
                "for device-specific back-pressure effects on valve lift."
            )
        st.caption(
            f"Choked mass flux at these conditions would be "
            f"{sizing['choked_mass_flux']:.0f} kg/(s·m²). Sizing basis: A = W/(K_d G) with "
            f"K_d = {kd:g}. For choked flow at fixed W, gas and K_d, doubling p₀ halves "
            f"the area; raising T₀ from {t_rel:.0f} K to {4 * t_rel:.0f} K doubles it."
        )
        render_what_to_notice(
            'Hold the other inputs fixed and raise back pressure from below the critical '
            'ratio. The required area stays flat until flow unchokes, then climbs. This '
            'plot describes ideal gas flow, not how valve lift responds to back pressure.'
        )
        render_plot(
            plot_relief_capacity(
                relief_capacity_curve(p_set * 1e5, t_rel, gamma_r, r_gas),
                sizing['back_pressure_ratio'],
            ),
            'relief-capacity',
        )

    st.markdown('#### 12.8.4 Worked example: a blocked-outlet case')
    example = relief_sizing(**defaults)
    hot = relief_sizing(**dict(defaults, t0=811.0))
    high_back = relief_sizing(**dict(defaults, back_pressure=8e5))
    prose(f'''This reproducible example uses the calculator's initial values, independently of your current edits: upstream stagnation pressure {defaults['p0'] / 1e5:g} bar a, temperature {defaults['t0']:g} K, required mass rate {defaults['required_flow']:g} kg/s, back pressure {defaults['back_pressure'] / 1e5:g} bar a, gamma {defaults['gamma']:g}, gas constant {defaults['gas_constant']:g} J/(kg·K), and discharge coefficient {defaults['discharge_coefficient']:g}.

**1 · Check choking.** The computed pressure ratio is {example['back_pressure_ratio']:.3f}, below the critical ratio {example['critical_ratio']:.3f}.

**2 · Calculate mass flux.** Substitution in the choked-flow equation gives G = {example['mass_flux']:.1f} kg/(s·m²).

**3 · Convert mass rate to area, then area to diameter.** A = W/(K_d G) = {example['area'] * 1e6:.1f} mm²; the equivalent circular bore is {example['diameter'] * 1000:.2f} mm. This is a model area, not a certified valve selection.

**4 · Separate the two sensitivity experiments.** Raising only back pressure to 8 bar a gives a ratio of {high_back['back_pressure_ratio']:.3f} and unchokes the flow. The model's mass flux falls by {100 * high_back['capacity_loss_vs_choked']:.1f}%.

Returning back pressure to its initial value and raising only temperature to 811 K increases area by a factor of {hot['area'] / example['area']:.3f}, to {hot['area'] * 1e6:.1f} mm². Bore increases by only {hot['diameter'] / example['diameter']:.3f}, to **{hot['diameter'] * 1000:.2f} mm**. Area follows the square root of temperature; diameter follows its fourth root. This temperature comparison holds the required mass rate fixed; an actual fire scenario requires its own release-rate calculation.''')
    render_self_check(
        'relief_self_check_backpressure',
        'An ideal fixed-area gas restriction is choked, discharging to a 1 bar a header. With upstream state unchanged, routing '
        'it to a 0.3 bar a vacuum header gives a capacity gain of…',
        ['about three times', 'none at all', 'about 40%'],
        'none at all',
        'While choked, the throat cannot detect downstream pressure — the mass flux contains '
        'no p_b term at fixed upstream state, gas and coefficient. Real valve and piping '
        'effects require a separate model.',
    )
    st.caption(
        'Model limits: single-phase ideal gas with constant gamma, fixed effective area and '
        'coefficient, no inlet line loss and no valve dynamics. Flashing, two-phase flow, '
        'real-gas properties and certified device selection require other methods. '
        'This lesson demonstrates a flow model rather than a complete relief-system design.'
    )
